#!/bin/bash

filter_name_and_mac() {
    grep --only-matching -Pe '^\d+:\s+.+?:|\s+link/ether ([a-f0-9]{2}:){5}[a-f0-9]{2}'
}

join_alt_lines() {
    # https://stackoverflow.com/a/8987297
    sed '$!N;s/\n/ /'
}

exec ip a | filter_name_and_mac | grep -ve 'lo:' | join_alt_lines | sed 's|link/ether||' | tr -s ' ' | sed 's/^[[:digit:]][[:digit:]]*:[[:blank:]]*//'

